version: '3.9'
services:
  web:
    image: php:8.2-apache
    container_name: php-apache
    icon url: https://github.com/nvm2go/iconbank/blob/main/internet.png?raw=true
    title: Hosting
    network: bridge
    environment:
      PMA_HOST: mydb
      PMA_PASSWORD: mypassword
      PMA_USER: myuser
      PMA_PORT: "3306"
    ports:
      - "81:80"
    volumes:
      - /DATA/AppData/app:/var/www/html/
    depends_on:
      - db
  db:
    image: linuxserver/mariadb:10.11.5
    container_name: mariadb
    network: bridge
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      PGID: "1000"
      PUID: "1000"
      REMOTE_SQL:
      TZ: ASIA/MAKASSAR
    volumes:
      - /DATA/AppData/mysql/config:/config
      - /DATA/AppData/mysql:/var/lib/mysql
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    network: bridge
    environment:
      PMA_PORT: "3306"
    ports:
      - "8181:8080"
    depends_on:
      - db
